### ISSUE TITLE
Why exactly do we need this

### ISSUE THREAD

**Issue by soenneker** [suzuki-shunsuke/reenable-automerge-action#2]
Hi there,

Thanks for the library. I've experienced this too... is this a Dependabot/Github bug? Shouldn't Dependabot be rebasing automatically, thus not disabling auto merge?

Thanks

**Comment by suzuki-shunsuke** [comment]
Hi,

I think Dependabot has nothing to do with this because this issue occurs even if you don't use Dependabot.

As described in README, this issue occurs when the base branch was modified.

https://github.com/suzuki-shunsuke/reenable-automerge-action#motivation

> auto-merge was automatically disabled 7 hours ago Base branch was modified

I guess this is not a bug but an undocumented specification of GitHub, but I'm not sure.

How about asking GitHub for help?

- https://github.com/orgs/community/discussions
- https://support.github.com/contact?tags=rr-general-technical
